language: node_js
node_js:
  - 7.8.0
before_script:
  - npm install

services:
  -postgresql

postgres:
 adapter: postgresql
 database: myapp_test
 username: postgres

after_success:
  - npm test
  - npm run coverage
