export const CREATE_USER = 'CREATE_USER';

export const CREATE_USER_SUCCESS = 'CREATE_USER_SUCCESS';

export const CREATE_USER_FAILURE = 'CREATE_USER_FAILURE';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const GET_USER_DOCUMENT = 'GET_USER_DOCUMENT';

export const DELETE_USER_DOCUMENT = 'DELETE_USER_DOCUMENT';

export const DELETE_USER_DOCUMENT_SUCCESS = 'DELETE_USER_DOCUMENT_SUCCESS';

export const DELETE_USER_DOCUMENT_FAILURE = 'DELETE_USER_DOCUMENT_FAILURE';

export const GET_ONE_DOCUMENT = 'GET_ONE_DOCUMENT';

export const GET_ONE_DOCUMENT_SUCCESS = 'GET_ONE_DOCUMENT_SUCCESS';

export const GET_ONE_DOCUMENT_FAILURE = 'GET_ONE_DOCUMENT_FAILURE';

export const CREATE_DOCUMENT = 'CREATE_DOCUMENT';

export const CREATE_DOCUMENT_SUCCESS = 'CREATE_DOCUMENT_SUCCESS';

export const CREATE_DOCUMENT_FAILURE = 'CREATE_DOCUMENT_FAILURE';

export const UPDATE_DOCUMENT = 'UPDATE_DOCUMENT';

export const UPDATE_DOCUMENT_SUCCESS = 'UPDATE_DOCUMENT_SUCCESS';

export const UPDATE_DOCUMENT_FAILURE = 'UPDATE_DOCUMENT_FAILURE';

export const GET_ALL_PUBLIC_DOCUMENTS = 'GET_ALL_PUBLIC_DOCUMENTS';

export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';

export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';

export const SEARCH_USER = 'SEARCH_USER';

export const SEARCH_PUBLIC_DOCUMENTS = 'SEARCH_PUBLIC_DOCUMENTS';

export const SEARCH_MY_DOCUMENTS = 'SEARCH_MY_DOCUMENTS';

export const DELETE_USER = 'DELETE_USER';

export const GET_ALL_ROLE_DOCUMENTS = 'GET_ALL_ROLE_DOCUMENTS';
